In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
np.loadtxt(fname = 'data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [12]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(type(data))
print(data)

<class 'numpy.ndarray'>
[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [13]:
print(data.shape)

(60, 40)


In [15]:
print('first value in data:', data[0, 0])
print('middle value in data:', data[29, 19])

first value in data: 0.0
middle value in data: 16.0


In [16]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [17]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [18]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [20]:
print(np.mean(data))

6.14875


In [21]:
import time
print(time.ctime())

Sun Sep  8 09:57:58 2024


In [22]:
maxval, minval, stdval = np.amax(data), np.amin(data), np.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [40]:
patient_0 = data[0, :] 
print('maximum inflammation for patient 0:', np.amax(patient_0))

print('maximum inflammation for patient 2:', np.amax(data[2, :]))

maximum inflammation for patient 0: 18.0
maximum inflammation for patient 2: 19.0


In [27]:
print(np.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [29]:
print(np.mean(data, axis=0).shape)

(40,)


In [31]:
print(np.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [41]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [43]:
print("value of element[:4] is:", element[:4])
print("value of element[4:] is:", element[4:])
print("value of element[:] is:", element[:])

value of element[:4] is: oxyg
value of element[4:] is: en
value of element[:] is: oxygen


In [45]:
print("element[-1] is:", element[-1])
print("element[-2] is:", element[-2])

element[-1] is: n
element[-2] is: e


In [46]:
print("what element[1:-1] does:", element[1:-1])

what element[1:-1] does: xyge


In [47]:
element = 'oxygen'
print('last three characters:', element[-3:])
element = 'carpentry'
print('last three characters:', element[-3:])
element = 'clone'
print('last three characters:', element[-3:])
element = 'hi'
print('last three characters:', element[-3:])

last three characters: gen
last three characters: try
last three characters: one
last three characters: hi


In [51]:
print("data[3:3, 4:4] produce:", data[3:3, 4:4])
print("data[3:3, :] produce:", data[3:3, :])

data[3:3, 4:4] produce: []
data[3:3, :] produce: []


In [52]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = ')
print(A)

B = np.hstack([A, A])
print('B = ')
print(B)

C = np.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
D = np.hstack((A[:, :1], A[:, 2:]))
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [58]:
patient3_week1 = data[3, :7]
print(patient3_week1)
np.diff(patient3_week1)

[0. 0. 2. 0. 4. 2. 2.]


array([ 0.,  2., -2.,  4., -2.,  0.])

In [62]:
np.diff(data, axis=1)

array([[ 0.,  1.,  2., ...,  1., -3.,  0.],
       [ 1.,  1., -1., ...,  0., -1.,  1.],
       [ 1.,  0.,  2., ...,  0., -1.,  0.],
       ...,
       [ 1.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  1., ..., -2.,  2., -2.],
       [ 0.,  1., -1., ..., -2.,  0., -1.]])

In [66]:
a = np.diff(data)
print(a)
print(np.size(a))
print(np.shape(a))

[[ 0.  1.  2. ...  1. -3.  0.]
 [ 1.  1. -1. ...  0. -1.  1.]
 [ 1.  0.  2. ...  0. -1.  0.]
 ...
 [ 1.  0.  0. ... -1.  0.  0.]
 [ 0.  0.  1. ... -2.  2. -2.]
 [ 0.  1. -1. ... -2.  0. -1.]]
2340
(60, 39)


In [67]:
np.amax(np.diff(data, axis=1), axis=1)

array([ 7., 12., 11., 10., 11., 13., 10.,  8., 10., 10.,  7.,  7., 13.,
        7., 10., 10.,  8., 10.,  9., 10., 13.,  7., 12.,  9., 12., 11.,
       10., 10.,  7., 10., 11., 10.,  8., 11., 12., 10.,  9., 10., 13.,
       10.,  7.,  7., 10., 13., 12.,  8.,  8., 10., 10.,  9.,  8., 13.,
       10.,  7., 10.,  8., 12., 10.,  7., 12.])

In [68]:
np.amax(np.absolute(np.diff(data, axis=1)), axis=1)

array([12., 14., 11., 13., 11., 13., 10., 12., 10., 10., 10., 12., 13.,
       10., 11., 10., 12., 13.,  9., 10., 13.,  9., 12.,  9., 12., 11.,
       10., 13.,  9., 13., 11., 11.,  8., 11., 12., 13.,  9., 10., 13.,
       11., 11., 13., 11., 13., 13., 10.,  9., 10., 10.,  9.,  9., 13.,
       10.,  9., 10., 11., 13., 10., 10., 12.])