In [1]:
x = 5

if x < 5:
    print("small")
else:
    print("big")

big


In [2]:
for i in range(x):
    print(i)

0
1
2
3
4


In [6]:
some_dict = {"word": 1, "another word": 2, "some other word": 3}

In [7]:
some_dict["some other word"]

3

In [10]:
for key in some_dict:
    print(key, ":", some_dict[key])

word : 1
another word : 2
some other word : 3


In [11]:
import numpy as np

some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [12]:
some_array[4]

4.4

In [13]:
for x in some_array:
    print(x)

0.0
1.1
2.2
3.3
4.4
5.5
6.6
7.7
8.8
9.9


In [14]:
some_dict = {"word": 1, "another word": 2, "some other word": 3}
some_dict.keys()

dict_keys(['word', 'another word', 'some other word'])

In [15]:
some_dict["something I made up"]

KeyError: 'something I made up'

In [16]:
some_dict["something I made up"] = 123
some_dict["something I made up"]

123

In [17]:
some_dict.values()

dict_values([1, 2, 3, 123])

In [18]:
some_dict.items()

for key, value in some_dict.items():
    print(key, value)

word 1
another word 2
some other word 3
something I made up 123


In [19]:
import numpy as np

some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
some_array[0]  # okay
some_array[1]  # okay
some_array[9]  # okay
some_array[10]  # not okay

IndexError: index 10 is out of bounds for axis 0 with size 10

In [20]:
len(some_array)

10

In [21]:
some_array[-1]

9.9

In [22]:
some_array[2:7]

array([2.2, 3.3, 4.4, 5.5, 6.6])

In [26]:
array3d = np.arange(2 * 3 * 5).reshape(2, 3, 5)
array3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [24]:
array3d[:, 1:, 1:]

array([[[ 6,  7,  8,  9],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [26, 27, 28, 29]]])

In [43]:
array3d[0, :, 2:]


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [44]:
some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
boolean_array = np.array(
    [True, True, True, True, True, False, True, False, True, False]
)

some_array[boolean_array]

array([0. , 1.1, 2.2, 3.3, 4.4, 6.6, 8.8])

In [45]:
some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
integer_array = np.array([0, 1, 2, 3, 4, 6, 8])

some_array[integer_array]

array([0. , 1.1, 2.2, 3.3, 4.4, 6.6, 8.8])

In [46]:
some_array[np.array([4, 2, 2, 2, 9, 8, 3])]

array([4.4, 2.2, 2.2, 2.2, 9.9, 8.8, 3.3])

In [47]:
even_valued_items = some_array * 10 % 2 == 0

some_array[even_valued_items]

array([0. , 2.2, 4.4, 6.6, 8.8])

In [49]:
x = 0

x > -10 & x < 10  # probably not what you expect!

False

In [50]:

(x > -10) & (x < 10)

True

In [51]:
even_valued_items = some_array * 10 % 2 == 0

In [52]:
even_valued_items = []

for x in some_array:
    even_valued_items.append(x * 10 % 2 == 0)