In [8]:
import ROOT
import pandas as pd
import numpy as np
from scipy.stats import norm

In [4]:
mean = 3.2
sigma = 1.3
gaussian_data = np.random.normal(loc=mean, scale=sigma, size = 10000)

In [5]:
x_var = ROOT.RooRealVar("x", "x", -20, 20)

In [6]:
mean_var = ROOT.RooRealVar("mean", "mean of gaussian", 0, -20, 20)
sigma_var = ROOT.RooRealVar("sigma", "std of gaussian", 1, 0, 10)

# create gaussian PDF using these variables
gauss = ROOT.RooGaussian("gauss", "gaussianPDF", x_var, mean_var, sigma_var)

[#0] WARNING:InputArguments -- The parameter 'sigma' with range [0, 10] of the RooGaussian 'gauss' exceeds the safe range of (0, inf). Advise to limit its range.


In [7]:
# assign x_var (the RooFit variable) to the gaussian data we made with numpy
data = ROOT.RooDataSet.from_numpy({'x':gaussian_data}, [x_var])

# fit our model to the data
gauss.fitTo(data)

# find out what mean and standard deviation it found from the fit
roofit_mean = gauss.getMean().getVal()
roofit_sigma = gauss.getSigma().getVal()

[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const optimization
Minuit2Minimizer: Minimize with max-calls 1000 convergence for edm < 1 strategy 1
Minuit2Minimizer : Valid minimum - status = 0
FVAL  = 16704.4757186868192
Edm   = 1.89964142842937024e-06
Nfcn  = 49
mean	  = 3.22185	 +/-  0.0128595	(limited)
sigma	  = 1.28595	 +/-  0.00909285	(limited)
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: deactivating const optimization


Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =       69359.35229 Edm =       72063.30371 NCalls =      9
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : 69359.35229
  Edm           : 72063.30371
  Internal parameters:	[                0     -0.927295218]	
  Internal gradient  :	[     -644367.6664     -331061.4495]	
  Internal covariance matrix:
[[  5.0000223e-07              0]
 [              0  7.3582302e-07]]]
Info in <Minuit2>: VariableMetricBuilder Start iterating until Edm is < 0.001 with call limit = 1000
Info in <Minuit2>: VariableMetricBuilder    0 - FCN =       69359.35229 Edm =       72063.30371 NCalls =      9
Info in <Minuit2>: VariableMetricBuilder    1 - FCN =       16766.82927 Edm =       2.772534759 NCalls =     18
Info in <Minuit2>: VariableMetricBuilder    2 - FCN =       16733.95308 Edm =        7.82382094 NCalls =     26
Info in <Minuit2>: VariableMetr

In [9]:
def normalize(hist):
    integral = 0.0
    for i in range(hist.GetNbinsX()+1):
        integral += hist.GetBinContent(i) * hist.GetBinWidth(i)
    hist.Scale(1.0 / integral)
    return hist

In [10]:
cb_data = np.genfromtxt('crystal-ball-dataset.txt')
x_min = min(cb_data)
x_max = max(cb_data)

In [11]:
m0 = ROOT.RooRealVar('m0', 'm0',                1, 1e-6, 1e6)
sigma = ROOT.RooRealVar('sigma', 'sigma',       1, 1e-6, 1e6)
alpha_l = ROOT.RooRealVar('alpha_l', 'alpha_l', 1, 1e-6, 1e6)
alpha_r = ROOT.RooRealVar('alpha_r', 'alpha_r', 1, 1e-6, 1e6)
eta_l = ROOT.RooRealVar('eta_l', 'eta_l',       1, 1e-6, 1e6)
eta_r = ROOT.RooRealVar('eta_r', 'eta_r',       1, 1e-6, 1e6)

x = ROOT.RooRealVar("x", "x", x_min, x_max)
crystal_ball = ROOT.RooCrystalBall("cb", "cb", x, m0,
                                   sigma,
                                   alpha_l, eta_l,
                                   alpha_r, eta_r)

In [12]:
data = ROOT.RooDataSet.from_numpy({'x':cb_data}, [x])
crystal_ball.fitTo(data)

[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const optimization
Minuit2Minimizer: Minimize with max-calls 3000 convergence for edm < 1 strategy 1
Minuit2Minimizer : Valid minimum - status = 0
FVAL  = 32744.5427988570918
Edm   = 7.52086370688576831e-06
Nfcn  = 248
alpha_l	  = 2.03235	 +/-  0.056049	(limited)
alpha_r	  = 1.00021	 +/-  0.0476832	(limited)
eta_l	  = 0.23916	 +/-  0.0551381	(limited)
eta_r	  = 1.88876	 +/-  0.166527	(limited)
m0	  = 1.41816	 +/-  0.0587834	(limited)
sigma	  = 3.03037	 +/-  0.0572285	(limited)
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: deactivating const optimization


Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =       33587.06208 Edm =       827.2494012 NCalls =     25
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : 33587.06208
  Edm           : 827.2494012
  Internal parameters:	[     -1.568796327     -1.568796327     -1.568796327     -1.568796327     -1.568796327     -1.568796327]	
  Internal gradient  :	[     -372598.2049      1744863.923     -486752.0064      634515.5183     -383250.2519     -919505.6545]	
  Internal covariance matrix:
[[  4.1001609e-10              0              0              0              0              0]
 [              0  2.9576039e-10              0              0              0              0]
 [              0              0  6.9145391e-10              0              0              0]
 [              0              0              0  5.1528756e-10              0              0]
 [              0         

In [13]:
print('Fitted results')
print(m0)
print(sigma)
print(alpha_l)
print(alpha_r)
print(eta_l)
print(eta_r)

Fitted results
RooRealVar::m0 = 1.41816 +/- 0.0586263  L(1e-06 - 1e+06) 

RooRealVar::sigma = 3.03037 +/- 0.056882  L(1e-06 - 1e+06) 

RooRealVar::alpha_l = 2.03235 +/- 0.0555292  L(1e-06 - 1e+06) 

RooRealVar::alpha_r = 1.00021 +/- 0.0476335  L(1e-06 - 1e+06) 

RooRealVar::eta_l = 0.23916 +/- 0.0547321  L(1e-06 - 1e+06) 

RooRealVar::eta_r = 1.88876 +/- 0.165347  L(1e-06 - 1e+06) 



In [14]:
# plot the gaussian data on a histogram
h = ROOT.TH1F("cb", "cb", 50, x_min, x_max)
for v in cb_data:
    h.Fill(v)
h = normalize(h)
    
# draw tgraph of fit line
fit_graph = ROOT.TGraph()
for v in np.linspace(x_min, x_max, 50000):
    x.setVal(v)
    fit_graph.SetPoint(fit_graph.GetN(), # set next point
                       v, # with this x
                       crystal_ball.getVal(x)) # and this y

# add legend
leg = ROOT.TLegend()
leg.AddEntry(h, 'Crystal Ball Data', 'lep')
leg.AddEntry(fit_graph, 'Fit', 'l')

# plot on canvas
c = ROOT.TCanvas()
h.Draw()
fit_graph.Draw('c, same')
leg.Draw('same')
c.SaveAs("crystal-ball.png")

Info in <TCanvas::Print>: png file crystal-ball.png has been created
