In [1]:
import numpy as np
arr_1 = np.array([3.3, 2.1, 4.4, 5.7, 8.9, 1.0])
arr_2 = np.array([6.1, 8.5, 1.1, 5.9, 1.2, 5.0])
arr_1 + arr_2

arr_1 / arr_2
arr_1 - arr_2
np.sum(arr_1)
np.sort(arr_2)

array([1.1, 1.2, 5. , 5.9, 6.1, 8.5])

In [2]:
import numpy as np
from time import process_time

a = np.linspace(-5,  12,   10000)   # 10000 equally spaced points from -5 --> 12
b = np.linspace(100, 108, 10000) # 10000 more equally spaced points from 100-->108


# pure python implementation
t1 = process_time()
dot_product = 0
for x,y in zip(a,b):
    dot_product += x*y
t2 = process_time()

py_time = t2 - t1
print('Python time: ', py_time)


# numpy implementation
t1 = process_time()
dot_product = np.dot(a,b)
t2 = process_time()

np_time = t2 - t1
print('Numpy time: ', np_time)

print('Numpy speed improvement: ', round(py_time / np_time), 'X faster')

Python time:  0.004699000000000009
Numpy time:  0.0005549999999998612
Numpy speed improvement:  8 X faster


In [3]:
import scipy.special as sc

# bessel function of first kind of real order
sc.jv(3, 1.4)

# binomial distribution CDF
sc.bdtr(12, 25, 0.5)

# gamma function
sc.gamma(12.3)

# error function of complex argument
sc.erf(1.1 + 2.3j)

# chebyshev polynomial evaluation
sc.eval_chebyt(4, 3.1)

# hermite polynomial evaluation
sc.hermite(8)


poly1d([ 2.56000000e+02,  0.00000000e+00, -3.58400000e+03,  4.54747351e-13,
        1.34400000e+04, -1.81898940e-12, -1.34400000e+04,  3.41060513e-13,
        1.68000000e+03])

In [4]:
import numpy as np
import scipy.integrate as integrate

def function_to_integrate(x, a, b):
    return a*np.tanh(np.sin(b-x))

result = integrate.quad(function_to_integrate,
                        -5.1, 3.3, # lower and upper limits
                        args=(1.2, 3.4)) # a and b in the function_to_integrate
print(result)

(1.556959479782644, 1.2469607747083757e-09)


In [5]:
import numpy as np
from scipy.optimize import root

def func(x):
    return x + 2 * np.cos(x)

sol = root(func, 0.3)
print(sol.x)


[-1.02986653]


In [6]:
from scipy.fft import fft
import numpy as np

x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
fft(x)


array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [7]:
import numpy as np
from scipy import linalg

A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print(A)
linalg.inv(A)


[[1 3 5]
 [2 5 1]
 [2 3 8]]


array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [8]:
import numpy as np
from scipy import linalg

A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print(A)

    
b = np.array([10, 8, 3])

# solve Ax = b
x = linalg.solve(A,b)
print(x)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[-9.28  5.16  0.76]


In [9]:
import numpy as np
from scipy import linalg

A = np.array([[1,2],[3,4]])
print(A)
linalg.det(A)


[[1 2]
 [3 4]]


-2.0

In [10]:
import numpy as np
from scipy import linalg

A = np.array([[1, 2], [3, 4]])
print(A)

la, v = linalg.eig(A)

print('Eigenvalue(s): ', la)
print('Eigenvector(s): ', v)


[[1 2]
 [3 4]]
Eigenvalue(s):  [-0.37228132+0.j  5.37228132+0.j]
Eigenvector(s):  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [11]:
from scipy.stats import norm

# probability at point
norm.pdf(0.2)

# probability less than that point
norm.cdf(0.2)

# random sampling
norm.rvs(size=5)


array([ 0.23628833, -0.7299472 , -0.48645937, -0.27573888, -0.71371307])

In [12]:
import numpy as np
from time import process_time


# generate uniformly random data between -5 and 5
data = np.random.uniform(-5, 5, size=100000)

# use 100 evenly spaced bins from -5 to 5
bins = np.linspace(-5, 5, 100)

# use inefficient, trivial looping to check each bin in normal python
t1 = process_time()

bin_indices_py = []
for x in data:
    for i in range(len(bins)-1):
        if (x >= bins[i] and x <= bins[i+1]):
            bin_indices_py.append(i)
            break # kill for loop when you find right bin

t2 = process_time()
python_time = t2 - t1

# use numpy.digitize for same task
t1 = process_time()

bin_indices_np = np.digitize(data, bins)

t2 = process_time()
numpy_time = t2 - t1

# print results
print('Python time: ', python_time)
print('Numpy time: ', numpy_time)
print('Numpy speed improvement: ', round(python_time / numpy_time), 'X faster')

Python time:  2.1811100000000003
Numpy time:  0.007526000000000366
Numpy speed improvement:  290 X faster


In [13]:
import numpy as np
from scipy import special, integrate, linalg

#---------------------
# Prob 1
#---------------------
print('Problem 1')

# using scipy.special.fresnel
z_vals = np.linspace(0, 5, 5)
fresnel_vals = np.array(special.fresnel(z_vals)).T # transpose it

# using scipy.integrate.quad
def fresnel_S_integrand(t):
    return np.sin(np.pi * (t**2) / 2)
def fresnel_C_integrand(t):
    return np.cos(np.pi * (t**2) / 2)

def fresnel_S(z):
    return integrate.quad(fresnel_S_integrand, 0, z)
def fresnel_C(z):
    return integrate.quad(fresnel_C_integrand, 0, z)

fresnel_vals_2 = []
for z in z_vals:
    fresnel_vals_2.append([fresnel_S(z),
                           fresnel_C(z)])
fresnel_vals_2 = np.array(fresnel_vals_2)

print('z', z)
print('Fresnel interals (method 1):', fresnel_vals)
print('Fresnel interals (method 2):', fresnel_vals_2)


#---------------------
# Prob 2
#---------------------
print('\n\nProblem 2')
x = np.linspace(0, 5, 5)
alpha = 2
y = special.jv(alpha, x)
print('alpha:', alpha)
print('x:', x)
print('y:', y)

#---------------------
# Prob 3
#---------------------
print('\n\nProblem 3')

def func(x,y):
    return 4*np.sin(x) - 4*x*y + 3*(x**2)*((y**4) - np.sin(x*y))

x_vals = np.array([-1, 1, 2, 5]).astype('float')
soln = integrate.solve_ivp(func,
                             t_span=(-1, 5),
                             y0=[0.0],
                             t_eval = x_vals)

print('x:', x_vals)
print('y:', soln.y)

#---------------------
# Prob 4
#---------------------
print('\n\nProblem 4')

R = np.array([[1, 1+1j, 2j],
              [1-1j, 5, -3],
              [-2j, -3, 0]])

r, psi = linalg.eig(R)
print('Eigenvalues:', r)
print('Eigenvector:', psi)

print('\n Eigenvalue %s corresponds to the eigenvector %s' %(r[-1], psi[:, -1]))

Problem 1
z 5.0
Fresnel interals (method 1): [[0.         0.        ]
 [0.65865551 0.68009074]
 [0.61918176 0.45741301]
 [0.5845332  0.49359046]
 [0.49919138 0.56363119]]
Fresnel interals (method 2): [[[0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00]]

 [[6.58655512e-01 7.31254514e-15]
  [6.80090741e-01 9.77482268e-15]]

 [[6.19181756e-01 1.16241472e-12]
  [4.57413010e-01 4.16495562e-14]]

 [[5.84533202e-01 6.78683529e-11]
  [4.93590463e-01 1.20126022e-10]]

 [[4.99191382e-01 8.38150451e-09]
  [5.63631189e-01 1.21691787e-09]]]


Problem 2
alpha: 2
x: [0.   1.25 2.5  3.75 5.  ]
y: [0.         0.17109113 0.44605906 0.41912837 0.04656512]


Problem 3
x: [-1.  1.  2.  5.]
y: [[ 0.          0.44293328  0.12155355 -0.00973444]]


Problem 4
Eigenvalues: [-2.80016977-1.33662690e-16j  2.22781013-6.45899823e-17j
  6.57235964-2.37919328e-17j]
Eigenvector: [[-0.08312116-0.5153606j   0.83350511+0.j          0.18032458+0.01570372j]
 [ 0.37128862+0.05541411j -0.12235779-0.2071796j   